name: pesca_app
description: "Un nuovo progetto Flutter per le previsioni di pesca."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  app_settings: ^5.0.0
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  fl_chart: ^1.1.1
  flutter_markdown: ^0.7.1  
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1  
  geolocator: ^14.0.2
  http: ^1.5.0
  intl: ^0.18.0
  light: ^4.1.0
  lottie: ^3.3.2
  palette_generator: ^0.3.3+3
  shared_preferences: ^2.2.3
  weather_icons: ^3.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/background_daily.jpg
    - assets/background_nocturnal.jpg
    - assets/background_rainy.jpg
    - assets/background_sunset.jpg
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic